[package]
name = "jwks-server"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
anyhow = "1.0.100"
base64 = "0.22.1"
chrono = "0.4.42"
jsonwebtoken = "9.3.1"
rand = "0.8"
rsa = "0.9.8"
serde = "1.0.225"
serde_json = "1.0.145"

[dev-dependencies]
serial_test = "3.2.0"
